n1 = int(input("Write a number to I could do his multiplication table "))
print("The multiplication table of the number {} is".format(n1))
print("{}x{}={}".format(n1,1,n1*1))
print("{}x{}={}".format(n1,2,n1*2))
print("{}x{}={}".format(n1,3,n1*3))
print("{}x{}={}".format(n1,4,n1*4))
print("{}x{}={}".format(n1,5,n1*5))
print("{}x{}={}".format(n1,6,n1*6))
print("{}x{}={}".format(n1,7,n1*7))
print("{}x{}={}".format(n1,8,n1*8))
print("{}x{}={}".format(n1,9,n1*9))
print("{}x{}={}".format(n1,10,n1*10))
