n1 = int(input("Write a number to I could do his multiplication table "))
print("The multiplication table of the number {} is".format(n1))
print(n1*1)
print(n1*2)
print(n1*3)
print(n1*4)
print(n1*5)
print(n1*6)
print(n1*7)
print(n1*8)
print(n1*9)
print(n1*10)
